### ISSUE TITLE
OndatoError.unexpectedInternalError  on IOS devices

### ISSUE THREAD

**Issue by SigoffNick** [ondato/ondato-sdk-flutter#10]
I have an issue with OndatoError.unexpectedInternalError on iOS.

Verification on iOS devices does not work. While on android devices verification is successful. When I trying to verify, the OndatoError.unexpectedInternalError is thrown. I have also tried to make the verification in the test application into the package result is the same. I have tested on a virtual devise IPhone 15 Pro(IOS 17.5) as well on a real device IPhone 12(IOS 16.2).

Flutter doctor
![Screenshot 2024-08-09 at 08 50 37](https://github.com/user-attachments/assets/005758ef-b2b2-4a14-8312-722c616e3d8c)

Logs
![Screenshot 2024-08-09 at 08 37 50 2](https://github.com/user-attachments/assets/fbbb7290-8e3a-408e-8f9d-ca1777586904)

![Screenshot 2024-08-09 at 08 38 25](https://github.com/user-attachments/assets/dd16f91e-3a1f-4651-a9be-5c24a7f89a5c)

**Comment by ondato-mobile** [comment]
Please try updating to the newest release. 

If the issue persists, please provide the returned exception and the console output.  The newest version has more detailed reporting and will help us pinpoint the issue faster.

**Comment by SigoffNick** [comment]
I updated the package. Now I have the following error
![Screenshot 2024-09-12 at 16 36 27](https://github.com/user-attachments/assets/d41b3ece-7482-43fa-ab78-fe70f7ebb277)
