### ISSUE TITLE
No static method bind

### ISSUE THREAD

**Issue by dipakravalVH** [ondato/ondato-sdk-flutter#7]
E/AndroidRuntime(17987): FATAL EXCEPTION: main
E/AndroidRuntime(17987): java.lang.NoSuchMethodError: No static method bind(Lkotlin/Pair;Lkotlin/reflect/KClass;)Lkotlin/Pair; in class Lorg/koin/dsl/DefinitionBindingKt; or its super classes (declaration of 'org.koin.dsl.DefinitionBindingKt' appears in /data/app/com.plutopecrypto.app-HjLeyIjO9RpsA9WKVg1lag==/base.apk!classes8.dex)
E/AndroidRuntime(17987): 	at e.v.invoke(SourceFile:138)
E/AndroidRuntime(17987): 	at org.koin.dsl.ModuleDSLKt.module(ModuleDSL.kt:44)
E/AndroidRuntime(17987): 	at org.koin.dsl.ModuleDSLKt.module$default(ModuleDSL.kt:42)
E/AndroidRuntime(17987): 	at u.b.invoke(SourceFile:93)
E/AndroidRuntime(17987): 	at u.c.startKoin(SourceFile:7)
E/AndroidRuntime(17987): 	at com.ondato.sdk.Ondato.startIdentification(SourceFile:6)
E/AndroidRuntime(17987): 	at com.kyc.ondato.ondato_flutter.OndatoFlutterPlugin.startIdentification(OndatoFlutterPlugin.kt:50)
E/AndroidRuntime(17987): 	at com.kyc.ondato.ondato_flutter.OndatoFlutterPlugin.onMethodCall(OndatoFlutterPlugin.kt:39)
E/AndroidRuntime(17987): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/AndroidRuntime(17987): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/AndroidRuntime(17987): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(17987): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(17987): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(17987): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(17987): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17987): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
E/AndroidRuntime(17987): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17987): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(17987): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
D/ViewRootImpl[MainActivity](17987): windowFocusChanged hasFocus=false inTouchMode=true
I/Process (17987): Sending signal. PID: 17987 SIG: 9 

Hiii, i faced this error in Flutter 3.19.3

Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ba39319843 (13 days ago) • 2024-03-07 15:22:21 -0600
Engine • revision 2e4ba9c6fb
Tools • Dart 3.3.1 • DevTools 2.31.1

kotlin-version: ext.kotlin_version = '1.8.0'

**Comment by dipakravalVH** [comment]
Hello, we are depend on this issue, 
This issue is also in the android side, so it is the critical issue of this SDK,
We don't have much time for this, So please fix this issue.

**Comment by dipakravalVH** [comment]
Any update on this issue?

**Comment by Svaike** [comment]
@dipakravalVH can you test if you face the same issue on the latest version (0.4.1)?

**Comment by dipakravalVH** [comment]
Hiii @Svaike thank you for replying here,
I'm facing the same issue in latest release also (0.4.1),
Can you please check this in kotlin-version: '1.8.0' and flutter version: 3.19.3,
This issue is still present in flutter & native android.
And i would like to request you to please update the repository.

**Comment by edgaras-simanavicius** [comment]
@dipakravalVH I took the [example](https://github.com/ondato/ondato-sdk-flutter/tree/main/example) from this repository and changed the kotlin version to 1.8.0. The project builds and runs fine.

Can you verify it is the same case for the example here for you? Have you tried updating flutter to the latest (3.19.4) version?

**Comment by dipakravalVH** [comment]
Hiii @edgaras-simanavicius, I took the example from this repository and changed the kotlin version to 1.8.0.
It's working fine, but if i create a new project and then add the package using github URL with reference of main branch it's not working. Also my previous version of flutter is 3.19.3 but as you told i have upgraded 3.19.4 but there is no any effect on this.

**Comment by dipakravalVH** [comment]
Hiii @Svaike, @edgaras-simanavicius, Finally i found the conflicted solution for this, 
I'm using wallet_connect_v2 package in my project, When i have removed this plugin then it's working properly.
There are something conflict with this package. Can you please try this with wallet_connect_v2 package?
