### ISSUE TITLE
face recognition localisation problem

### ISSUE THREAD

**Issue by martunta** [ondato/ondato-sdk-flutter#8]
I have an issue with FACETEC localization on iOS. 

When the face recognition is launched, all the translations dissapear. Rest of the Ondato plugin is nicely localized, all the english text shows up, but for this part, this FACETEC thing, there are no texts.

This is only on iOS, on Android it works fine. So my guess is that Ondato iOS library depends on some third party library called FACETEC, and maybe that one is not working properly. Again, to repeat, just for iOS, so it is unlikely that it is flutter plugin that is broken.

using latest version that was released 2 months ago.

**Comment by Svaike** [comment]
@martunta did you try to run the example app to see if the same issue happens?

**Comment by martunta** [comment]
No I did not. Will try today. 
But let's imagine that the problem is not replicated in example app. There all is good. Then what can I do in my app to fix it? Any thoughts what might be wrong? if localisation is fine in rest of the Ondato plugin, except the FACETEC part?
